import Foundation

@main
struct ClaudeUsageCheck {
    static func main() throws {
        let fm = FileManager.default
        let root = fm.temporaryDirectory.appendingPathComponent(UUID().uuidString)
        let config = root.appendingPathComponent("config"), dir = root.appendingPathComponent("support folder")
        try fm.createDirectory(at: config, withIntermediateDirectories: true)
        defer { try? fm.removeItem(at: root) }
        let url = config.appendingPathComponent("settings.json")
        let original: [String: Any] = ["type":"command", "command":"printf original", "padding":3, "refreshInterval":12]
        try ClaudeUsageBridge.write(["statusLine":original,"unrelated":"preserve"], to:url)
        let fake = root.appendingPathComponent("executable")
        precondition(ClaudeCodeSetup.parseStatus(Data(#"{"loggedIn":false,"authMethod":"none"}"#.utf8)) == .signedOut)
        precondition(ClaudeCodeSetup.parseStatus(Data(#"{"loggedIn":true,"authMethod":"claude.ai","email":"PRIVATE"}"#.utf8)) == .signedIn)
        precondition(ClaudeCodeSetup.parseStatus(Data(#"{"loggedIn":true,"authMethod":"api_key"}"#.utf8)) == .unsupported)
        precondition(ClaudeCodeSetup.parseStatus(Data("invalid".utf8)) == .unavailable)
        try Data("#!/bin/sh\nprintf '%s' '{\"loggedIn\":false,\"authMethod\":\"none\"}'\nexit 1\n".utf8).write(to: fake)
        try fm.setAttributes([.posixPermissions: 0o700], ofItemAtPath: fake.path)
        precondition(ClaudeCodeSetup.status(executable: fake) == .signedOut, "Exit 1 is a valid signed-out response")
        try Data("#!/bin/sh\nexec sleep 10\n".utf8).write(to: fake)
        let started = Date()
        precondition(ClaudeCodeSetup.status(executable: fake, timeoutInterval: 0.1) == .unavailable)
        precondition(Date().timeIntervalSince(started) < 3, "Auth checks must have a bounded timeout")
        let mockCLI = root.appendingPathComponent("claude's mock")
        let log = root.appendingPathComponent("setup calls")
        try Data(("#!/bin/sh\nprintf '%s\\n' \"$*\" >> " + ClaudeUsageBridge.quote(log.path) + "\n").utf8).write(to: mockCLI)
        try fm.setAttributes([.posixPermissions: 0o700], ofItemAtPath: mockCLI.path)
        for login in [true, false] {
            let launch = root.appendingPathComponent("launch.command")
            try Data(ClaudeCodeSetup.launcher(executable: mockCLI, config: config, session: root, needsLogin: login).utf8).write(to: launch)
            let process = Process()
            process.executableURL = URL(fileURLWithPath: "/bin/zsh")
            process.arguments = [launch.path]
            try process.run()
            process.waitUntilExit()
            precondition(process.terminationStatus == 0)
        }
        let calls = try String(contentsOf: log, encoding: .utf8)
        precondition(calls == "auth login\n\n\n", "Login only when needed, then open the interactive session; shell quoting handles apostrophes")
        try Data("#!/bin/sh\nexit 1\n".utf8).write(to: mockCLI)
        let failureScript = root.appendingPathComponent("failure.command")
        try Data(ClaudeCodeSetup.launcher(executable: mockCLI, config: config, session: root, needsLogin: true).utf8).write(to: failureScript)
        let failure = Process()
        failure.executableURL = URL(fileURLWithPath: "/bin/zsh")
        failure.arguments = [failureScript.path]
        try failure.run()
        failure.waitUntilExit()
        precondition(failure.terminationStatus == 1, "Failed login must stop before opening a conversation")
        try Data("helper".utf8).write(to: fake)
        try ClaudeUsageBridge.install(executable:fake, config:config, dir:dir)
        precondition(ClaudeUsageBridge.connected(config:config, dir:dir))
        let settings = try ClaudeUsageBridge.object(url)
        precondition(settings["unrelated"] as? String == "preserve")
        precondition((settings["statusLine"] as? [String:Any])?["padding"] as? Int == 3)
        try ClaudeUsageBridge.install(executable:fake, config:config, dir:dir)
        let backup = try ClaudeUsageBridge.object(dir.appendingPathComponent("claude-statusline-backup.json"))
        precondition((backup["previousStatusLine"] as? [String:Any])?["command"] as? String == "printf original", "Reconnect must not replace the original backup")
        let now = Date(timeIntervalSince1970:1_800_000_000)
        let input = #"{"rate_limits":{"five_hour":{"used_percentage":25,"resets_at":1800003600},"seven_day":{"used_percentage":60,"resets_at":1800300000}},"prompt":"DO-NOT-STORE","session_id":"PRIVATE","model":{"id":"PRIVATE"}}"#
        try ClaudeUsageBridge.capture(Data(input.utf8),dir:dir,now:now)
        let dataURL = dir.appendingPathComponent("claude-quota.json")
        let stored = try Data(contentsOf:dataURL)
        let snapshot = try JSONDecoder().decode(ClaudeQuotaSnapshot.self,from:stored)
        precondition(snapshot.quotaWindows.count == 2)
        precondition(snapshot.quotaWindows.compactMap(\.remaining).min() == 40)
        precondition(!String(decoding:stored,as:UTF8.self).contains("PRIVATE"))
        precondition(!String(decoding:stored,as:UTF8.self).contains("DO-NOT-STORE"))
        try ClaudeUsageBridge.capture(Data("{}".utf8),dir:dir,now:now.addingTimeInterval(10))
        precondition((try? Data(contentsOf:dataURL)) == stored, "Startup callback must not renew old data")
        try ClaudeUsageBridge.capture(Data(#"{"rate_limits":{"five_hour":{"used_percentage":999,"resets_at":1800003600},"seven_day":{"used_percentage":20,"resets_at":1799990000}}}"#.utf8),dir:dir,now:now)
        precondition((try? Data(contentsOf:dataURL)) == stored, "Invalid or expired windows must not overwrite valid data")
        try ClaudeUsageBridge.disconnect(config:config,dir:dir)
        let restored = try ClaudeUsageBridge.object(url)
        precondition((restored["statusLine"] as? [String:Any])?["command"] as? String == "printf original")
        precondition(restored["unrelated"] as? String == "preserve")
        precondition(!fm.fileExists(atPath:dataURL.path))
        try ClaudeUsageBridge.write(["unrelated":"preserve"],to:url)
        try ClaudeUsageBridge.install(executable:fake,config:config,dir:dir)
        try ClaudeUsageBridge.disconnect(config:config,dir:dir)
        let withoutStatus = try ClaudeUsageBridge.object(url)
        precondition(withoutStatus["statusLine"] == nil)
        let forwarded = root.appendingPathComponent("forwarded-input")
        try ClaudeUsageBridge.write(["previousStatusLine":["command":"cat > " + ClaudeUsageBridge.quote(forwarded.path)]], to:dir.appendingPathComponent("claude-statusline-backup.json"))
        ClaudeUsageBridge.run(input:Data(input.utf8),dir:dir)
        let forwardedData = try Data(contentsOf:forwarded)
        precondition(forwardedData == Data(input.utf8), "Original command must receive the unchanged stdin payload")
        print("Claude bridge passed: config preservation, backup, idempotence, disconnect, quota-only storage, missing/invalid/expired data")
    }
}
